version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    environment:
      - ENV=${ENV}
      - HTTP_PORT=${HTTP_PORT}
      - USER_SRV_DOMAIN=${USER_SRV_DOMAIN}
      - USER_SRV_PORT=${USER_SRV_PORT}
      - RMQ_USER=${RMQ_USER}
      - RMQ_PASS=${RMQ_PASS}
      - RMQ_DOMAIN=${RMQ_DOMAIN}
      - RMQ_PORT=${RMQ_PORT}
      - REDIS_DOMAIN=${REDIS_DOMAIN}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASS=${REDIS_PASS}

    volumes:
      - ..:/workspaces:cached

    command: sleep infinity

    network_mode: "host"
