version: "3.8"

services:
  event-broker:
    container_name: rabbitmq
    image: rabbitmq:3-management
    env_file: env

    ports:
      - "5672:5672"
      - "15672:15672"
  
  cache:
    container_name: redis
    image: redis:7.2.4

    ports:
      - "6379:6379"
  
  cache-dashboard:
    container_name: insight
    image: redislabs/redisinsight

    ports:
      - "8001:8001"
